base_url = "https://elephantry.github.io"
compile_sass = true
build_search_index = false

highlight_code = true
highlight_theme = "monokai"

[markdown]
highlight_code = true
highlight_theme = "monokai"

[extra]
