on: push
name: Build and deploy GH Pages
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: borales/actions-yarn@v5.0.0
      with:
        cmd: install
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.19.2
      env:
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
